apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: my-super-secret-token-2024
    jsonData:
      version: Flux
      organization: university
      defaultBucket: exercises
      tlsSkipVerify: true
    isDefault: true
