# Wejścia - skąd zbierać dane
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  fieldpass = ["usage_user", "usage_system", "usage_idle"]

[[inputs.mem]]
  fieldpass = ["used_percent", "available"]

[[inputs.disk]]
  mount_points = ["/"]
  fieldpass = ["used_percent"]

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  container_names = []

# Wyjście - gdzie wysyłać dane
[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  token = "my-super-secret-token-2024"
  organization = "university"
  bucket = "exercises"
